---

version: 2

updates:
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain pip packages for acars_router
  - package-ecosystem: "pip"
    directory: "/acars_router"
    schedule:
      interval: "daily"
