FROM rust:1.64.0-bullseye as builder
WORKDIR /tmp/acars_router
# hadolint ignore=DL3008,DL3003,SC1091
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev
COPY . .

RUN cargo build --release
