FROM rust:1.68.2-bullseye as builder
WORKDIR /tmp/acars_router
# hadolint ignore=DL3008,DL3003,SC1091,DL3009
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev
COPY . .

RUN cargo build --release

FROM scratch
COPY --from=builder /tmp/acars_router/target/release/acars_router /acars_router
