FROM rust:1.80.1 as builder
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
WORKDIR /tmp/acars_router
# hadolint ignore=DL3008,DL3003,SC1091,DL3009
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev
COPY . .

RUN cargo build --release

FROM scratch
COPY --from=builder /tmp/acars_router/target/release/acars_router /acars_router
