#!/command/with-contenv bash
# shellcheck shell=bash

AR_COMMAND=()

# ACARS Input

if [[ -n $AR_LISTEN_UDP_ACARS ]]; then
    AR_COMMAND+=("--listen-udp-acars" "$AR_LISTEN_UDP_ACARS")
fi

if [[ -n $AR_LISTEN_TCP_ACARS ]]; then
    AR_COMMAND+=("--listen-tcp-acars" "$AR_LISTEN_TCP_ACARS")
fi

if [[ -n $AR_LISTEN_ZMQ_ACARS ]]; then
    AR_COMMAND+=("--listen-zmq-acars" "$AR_LISTEN_ZMQ_ACARS")
fi

if [[ -n $AR_RECV_TCP_ACARS ]]; then
    AR_COMMAND+=("--receive-tcp-acars" "$AR_RECV_TCP_ACARS")
fi

if [[ -n $AR_RECV_ZMQ_ACARS ]]; then
    AR_COMMAND+=("--receive-zmq-acars" "$AR_RECV_ZMQ_ACARS")
fi

# VDLM2 input

if [[ -n $AR_LISTEN_UDP_VDLM2 ]]; then
    AR_COMMAND+=("--listen-udp-vdlm2" "$AR_LISTEN_UDP_VDLM2")
fi

if [[ -n $AR_LISTEN_TCP_VDLM2 ]]; then
    AR_COMMAND+=("--listen-tcp-vdlm2" "$AR_LISTEN_TCP_VDLM2")
fi

if [[ -n $AR_LISTEN_ZMQ_VDLM2 ]]; then
    AR_COMMAND+=("--listen-zmq-vdlm2" "$AR_LISTEN_ZMQ_VDLM2")
fi

if [[ -n $AR_RECV_TCP_VDLM2 ]]; then
    AR_COMMAND+=("--receive-tcp-vdlm2" "$AR_RECV_TCP_VDLM2")
fi

if [[ -n $AR_RECV_ZMQ_VDLM2 ]]; then
    AR_COMMAND+=("--receive-zmq-vdlm2" "$AR_RECV_ZMQ_VDLM2")
fi

# HFDL input

if [[ -n $AR_LISTEN_UDP_HFDL ]]; then
    AR_COMMAND+=("--listen-udp-hfdl" "$AR_LISTEN_UDP_HFDL")
fi

if [[ -n $AR_LISTEN_TCP_HFDL ]]; then
    AR_COMMAND+=("--listen-tcp-hfdl" "$AR_LISTEN_TCP_HFDL")
fi

if [[ -n $AR_LISTEN_ZMQ_HFDL ]]; then
    AR_COMMAND+=("--listen-zmq-hfdl" "$AR_LISTEN_ZMQ_HFDL")
fi

if [[ -n $AR_RECV_TCP_HFDL ]]; then
    AR_COMMAND+=("--receive-tcp-hfdl" "$AR_RECV_TCP_HFDL")
fi

if [[ -n $AR_RECV_ZMQ_HFDL ]]; then
    AR_COMMAND+=("--receive-zmq-hfdl" "$AR_RECV_ZMQ_HFDL")
fi

# IMSL input

if [[ -n $AR_LISTEN_UDP_IMSL ]]; then
    AR_COMMAND+=("--listen-udp-imsl" "$AR_LISTEN_UDP_IMSL")
fi

if [[ -n $AR_LISTEN_TCP_IMSL ]]; then
    AR_COMMAND+=("--listen-tcp-imsl" "$AR_LISTEN_TCP_IMSL")
fi

if [[ -n $AR_LISTEN_ZMQ_IMSL ]]; then
    AR_COMMAND+=("--listen-zmq-imsl" "$AR_LISTEN_ZMQ_IMSL")
fi

if [[ -n $AR_RECV_TCP_IMSL ]]; then
    AR_COMMAND+=("--receive-tcp-imsl" "$AR_RECV_TCP_IMSL")
fi

if [[ -n $AR_RECV_ZMQ_IMSL ]]; then
    AR_COMMAND+=("--receive-zmq-imsl" "$AR_RECV_ZMQ_IMSL")
fi

# IRDM input

if [[ -n $AR_LISTEN_UDP_IRDM ]]; then
    AR_COMMAND+=("--listen-udp-irdm" "$AR_LISTEN_UDP_IRDM")
fi

if [[ -n $AR_LISTEN_TCP_IRDM ]]; then
    AR_COMMAND+=("--listen-tcp-irdm" "$AR_LISTEN_TCP_IRDM")
fi

if [[ -n $AR_LISTEN_ZMQ_IRDM ]]; then
    AR_COMMAND+=("--listen-zmq-irdm" "$AR_LISTEN_ZMQ_IRDM")
fi

if [[ -n $AR_RECV_TCP_IRDM ]]; then
    AR_COMMAND+=("--receive-tcp-irdm" "$AR_RECV_TCP_IRDM")
fi

if [[ -n $AR_RECV_ZMQ_IRDM ]]; then
    AR_COMMAND+=("--receive-zmq-irdm" "$AR_RECV_ZMQ_IRDM")
fi

# ACARS Output

if [[ -n $AR_SEND_UDP_ACARS ]]; then
    AR_COMMAND+=("--send-udp-acars" "$AR_SEND_UDP_ACARS")
fi

if [[ -n $AR_SEND_TCP_ACARS ]]; then
    AR_COMMAND+=("--send-tcp-acars" "$AR_SEND_TCP_ACARS")
fi

if [[ -n $AR_SERVE_TCP_ACARS ]]; then
    AR_COMMAND+=("--serve-tcp-acars" "$AR_SERVE_TCP_ACARS")
fi

if [[ -n $AR_SERVE_ZMQ_ACARS ]]; then
    AR_COMMAND+=("--serve-zmq-acars" "$AR_SERVE_ZMQ_ACARS")
fi

# VDLM2 Output

if [[ -n $AR_SEND_UDP_VDLM2 ]]; then
    AR_COMMAND+=("--send-udp-vdlm2" "$AR_SEND_UDP_VDLM2")
fi

if [[ -n $AR_SEND_TCP_VDLM2 ]]; then
    AR_COMMAND+=("--send-tcp-vdlm2" "$AR_SEND_TCP_VDLM2")
fi

if [[ -n $AR_SERVE_TCP_VDLM2 ]]; then
    AR_COMMAND+=("--serve-tcp-vdlm2" "$AR_SERVE_TCP_VDLM2")
fi

if [[ -n $AR_SERVE_ZMQ_VDLM2 ]]; then
    AR_COMMAND+=("--serve-zmq-vdlm2" "$AR_SERVE_ZMQ_VDLM2")
fi

# HFDL Output

if [[ -n $AR_SEND_UDP_HFDL ]]; then
    AR_COMMAND+=("--send-udp-hfdl" "$AR_SEND_UDP_HFDL")
fi

if [[ -n $AR_SEND_TCP_HFDL ]]; then
    AR_COMMAND+=("--send-tcp-hfdl" "$AR_SEND_TCP_HFDL")
fi

if [[ -n $AR_SERVE_TCP_HFDL ]]; then
    AR_COMMAND+=("--serve-tcp-hfdl" "$AR_SERVE_TCP_HFDL")
fi

if [[ -n $AR_SERVE_ZMQ_HFDL ]]; then
    AR_COMMAND+=("--serve-zmq-hfdl" "$AR_SERVE_ZMQ_HFDL")
fi

# IMSL Output

if [[ -n $AR_SEND_UDP_IMSL ]]; then
    AR_COMMAND+=("--send-udp-imsl" "$AR_SEND_UDP_IMSL")
fi

if [[ -n $AR_SEND_TCP_IMSL ]]; then
    AR_COMMAND+=("--send-tcp-imsl" "$AR_SEND_TCP_IMSL")
fi

if [[ -n $AR_SERVE_TCP_IMSL ]]; then
    AR_COMMAND+=("--serve-tcp-imsl" "$AR_SERVE_TCP_IMSL")
fi

if [[ -n $AR_SERVE_ZMQ_IMSL ]]; then
    AR_COMMAND+=("--serve-zmq-imsl" "$AR_SERVE_ZMQ_IMSL")
fi

# IRDM Output

if [[ -n $AR_SEND_UDP_IRDM ]]; then
    AR_COMMAND+=("--send-udp-irdm" "$AR_SEND_UDP_IRDM")
fi

if [[ -n $AR_SEND_TCP_IRDM ]]; then
    AR_COMMAND+=("--send-tcp-irdm" "$AR_SEND_TCP_IRDM")
fi

if [[ -n $AR_SERVE_TCP_IRDM ]]; then
    AR_COMMAND+=("--serve-tcp-irdm" "$AR_SERVE_TCP_IRDM")
fi

if [[ -n $AR_SERVE_ZMQ_IRDM ]]; then
    AR_COMMAND+=("--serve-zmq-irdm" "$AR_SERVE_ZMQ_IRDM")
fi

/opt/acars_router "${AR_COMMAND[@]}"
