#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if /opt/acars_router.x86_64 --version > /dev/null 2>&1; then
    /opt/acars_router.x86_64

elif /opt/acars_router.aarch64 --version > /dev/null 2>&1; then
    /opt/acars_router.aarch64

elif /opt/acars_router.armv7 --version > /dev/null 2>&1; then
    /opt/acars_router.armv7

elif /opt/acars_router --version /dev/null 2>&1; then
    /opt/acars_router

else
    >&2 echo "ERROR: Unsupported architecture"
    sleep 60
    exit 1
fi
