#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DEBUG_LEVEL=()

if [[ ${AR_VERBOSITY,,} =~ debug || $AR_VERBOSITY -eq 1 ]]; then
    DEBUG_LEVEL+=("-v")
elif [[ ${AR_VERBOSITY,,} =~ trace  || $AR_VERBOSITY -ge 2 ]]; then
    DEBUG_LEVEL+=("-vv")
fi

/opt/acars_router "${DEBUG_LEVEL[@]}"
