#!/usr/bin/env python3

import socket
import argparse
import logging
import time
import json
from pprint import pprint

if __name__ == "__main__":

    host = "127.0.0.1"
    port = 15555

    # configure logging: base logger
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s [%(levelname)s] [%(name)s] %(message)s')
    logger = logging.getLogger(f'{host}:{port}')
    logger.setLevel(logging.DEBUG)

    # loop until the session is disconnected
    while True:

        # prepare socket
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:

            # set up socket
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

            # attempt connection
            logger.debug("attempting to connect")

            # set socket connect timeout
            sock.settimeout(1)

            # attempt to connect
            try:
                sock.connect((host, port))
            except Exception as e:
                logger.error(f"connection error: {e}")
                time.sleep(1)

            # if connected with no exception
            else:
                logger.info("connection established")
                sock.settimeout(1)

                # while connected
                while True:

                    # try to receive data
                    try:
                        data = sock.recv(16384)

                    except TimeoutError:
                        pass

                    except Exception as e:
                        logger.error(f"error receiving data: {e}")

                    # if data received with no exception
                    else:

                        # if we received something
                        if data:

                            # initially, we attempt to decode the whole message
                            decode_to_char = len(data)

                            # counter to prevent getting stuck in an infinite loop (shouldn't happen as everything is in try/except, but just to be sure)
                            decode_attempts = 0

                            # while there is data left to decode:
                            while len(data) > 0:

                                # attempt to deserialise
                                try:
                                    deserialised_json = json.loads(data[:decode_to_char])

                                # if there is extra data, attempt to decode as much as we can next iteration of loop
                                except json.decoder.JSONDecodeError as e:
                                    decode_to_char = e.pos

                                # if an exception, log and continue
                                except Exception as e:
                                    logger.error(f"invalid JSON received: {data}, exception: {e}")
                                    break

                                # if there was no exception:
                                else:

                                    # ensure json.loads resulted in a dict
                                    if type(deserialised_json) != dict:
                                        logger.debug(f"invalid JSON received: json.loads on raw_json returned non-dict object: {data}")

                                    # if it is a dict...
                                    else:

                                        # print json
                                        pprint(deserialised_json)

                                        # remove the json we've already serialised from the input
                                        data = data[decode_to_char:]

                                # ensure we're not stuck in an infinite loop (unlikely there'd be 100 parts of json in a message. I've only ever seen up to 2.)
                                if decode_attempts > 100:
                                    logger.error(f"infinite loop deserialising: {data}")
                                    break
                                else:
                                    decode_attempts += 1

                        # if we received nothing, then "connection lost"
                        else:
                            logger.info("connection lost")

                            # close the socket
                            sock.close()

                            # sleep for a second (slow down reconnection attempts)
                            time.sleep(1)

                            # break out of inner loop, so reconnection can happen
                            break